// <auto-generated />
using CongestionTaxCalculator.Contexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CongestionTaxCalculator.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20231123102557_Init")]
    partial class Init
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.0");

            modelBuilder.Entity("CongestionTaxCalculator.Models.HourFee", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("EndHour")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Fee")
                        .HasColumnType("INTEGER");

                    b.Property<string>("StartHour")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Fees");
                });
#pragma warning restore 612, 618
        }
    }
}
